27 setup travis ci
AgileVentures/agile-ventures-website-react-front-end pull request #32
Opened 2018-12-11 01:55 UTC by FedericoEsparza

fixes #27

2018-12-11 12:13 UTC, Kachulio1 requested changes

2018-12-11 12:13 UTC, Kachulio1 commented on .travis.yml
> +  - yarn run build
Add a new line.

2018-12-12 09:35 UTC, FedericoEsparza commented on .travis.yml
> +  - yarn run build
@Kachulio1 Done

2018-12-12 11:07 UTC, Kachulio1 approved these changes

2018-12-12 11:07 UTC, merged